apiVersion: batch/v1
kind: Job
metadata:
   name: init
spec:
    template:
        metadata:
            labels:
                app: producteur-lab9
        spec:
            restartPolicy: OnFailure
            containers:
            - name: batch-init
              image: alpine:3.16
              volumeMounts:
              - name: backup
                mountPath: /mnt/backup
              command:  command: ["sleep","3600"]
            volumes:
            - name: backup
              persistentVolumeClaim: 
                claimName: backup-claim


