apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab12-ingress-domain
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dep51.formation.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: lab12-httpd-service
            port:
              number: 80
  - host: dep52.formation.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: lab12-nginx-service
            port:
              number: 80