apiVersion: apps/v1
kind: Deployment
metadata:
   name: lab12-nginx-deployment
   labels:
    app: nginx
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
            - name: www-nginx
              image: nginx:alpine
              ports:
              - containerPort: 80

            

