apiVersion: apps/v1
kind: Deployment
metadata:
   name: lab12-httpd-deployment
   labels:
    app: httpd
spec:
    replicas: 2
    selector:
        matchLabels:
            app: httpd
    template:
        metadata:
            labels:
                app: httpd
        spec:
            containers:
            - name: www-httpd
              image: httpd:alpine
              ports:
              - containerPort: 80

            

