apiVersion: apps/v1
kind: Deployment
metadata:
   name: lab12-httpd-deployment
   labels:
    app1: web-httpd
spec:
    replicas: 1
    selector:
        matchLabels:
            app1: web-httpd
    template:
        metadata:
            labels:
                app1: web-httpd
        spec:
            containers:
            - name: web-httpd
              image: httpd:alpine
              ports:
              - containerPort: 80

            

