apiVersion: apps/v1
kind: Deployment
metadata:
   name: lab12-nginx-deployment
   labels:
    app2: web-nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app2: web-nginx
    template:
        metadata:
            labels:
                app2: web-nginx
        spec:
            containers:
            - name: web-nginx
              image: nginx:alpine
              ports:
              - containerPort: 80

            

