apiVersion: apps/v1
kind: DeamonSet
metadata:
   name: debug-lab4
spec:
    selector:
        matchLabels:
            app: debug-lab4
    template:
        metadata:
            labels:
                app: debug-lab4
        spec:
            containers:
            - name: debug-lab4
              image: alpine:3.16
              command: ["sleep","3600"]

