apiVersion: apps/v1
kind: Deployment
metadata:
   name: web-lab4
   labels:
    app: web
spec:
    replicas: 8
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            labels:
                app: web
        spec:
            containers:
            - name: www
              image: nginx:1.17
              ports:
              - containerPort: 80