apiVersion: v1
kind: Pod
metadata:
   name: alpine
spec:
    containers:
        - name: alpine
          image: alpine:3.16
          command: ["sleep","3600"]
    affinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
                - web