apiVersion: apps/v1
kind: Deployment
metadata:
   name: web-lab6
   labels:
    app: web
spec:
    replicas: 2
    selector:
        matchLabels:
            app: web
    template:
        metadata:
            labels:
                app: web
        spec:
            containers:
            - name: www
              image: httpd:alpin
              ports:
              - containerPort: 80
            volumeMounts:
            - name: web
              mountPath: /usr/local/apache2/htdocs/
            volumes:
            - name: web
              persistentVolumeClaim:
                claimName: web-claim
            

